# Generated by Django 4.0.3 on 2022-05-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0002_remove_team_id_team_member1_team_member2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Team_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
