# Generated by Django 4.0.3 on 2022-05-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0005_alter_team_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Team_id',
            new_name='id',
        ),
    ]
