# Generated by Django 4.0.3 on 2022-05-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0006_rename_team_id_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='id',
            new_name='Team_id',
        ),
    ]
