# Generated by Django 4.0.3 on 2022-05-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0008_team_team_info_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member2',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='member3',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='member4',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
